### ISSUE TITLE
Create "Word of the day" view (subpage)

### ISSUE THREAD

**Issue by zkunik** [tqZK/harc_game_web#24]
- available to everyone (including not logged in users)
- for now - empty subpage
- add button to the navbar

This subpage will be used to see:
- current riddle (for given day)
- tommorow's riddle (for next day)
- form to check if a user solved riddle (current and next day) correctly
- all previous riddles with words of the day (answers)

**Comment by wdoganowski** [comment]
Jutro sie zabiorę

**Comment by wdoganowski** [comment]
Widzę, że nie zrobiłem jeszcze tylko sprawdzenia jutrzejszego pytania.
Trzeba tez zmienić metoda weryfikacji.
To jutro
Na teraz jest PR #33
