### ISSUE TITLE
Add "generate report" feature

### ISSUE THREAD

**Issue by zkunik** [tqZK/harc_game_web#30]
On "report" subpage (avaliable only to admin) there should be custom reports with how many a given user has earned for completing tasks in given week.
Week starts on Saturday and ends on Friday.
Reports should be divided in the subpage with a line and information for which week they are generated.

1. for each player
2. get all `DocumentedTask`s that have `is_accepted=True` for given player
2. sum `prize` values, but remember to deduct `tax` (`Team` model) that should go to team leader (`is_team_leader` in `Scout` model) (this tax should be added to team leader sum of prizes)
3. print report in this form (new line for each user):
```
/pay username prize_sum
/pay username2 prize_sum2
```
e.g.
```
/pay Zuza 42
/pay Hubert 10
```
Also, some tasks have `extra_prize`. These should be reported in this way (new line for each user and each extra prize):
```
/give username extra_prize1
/give username extra_prize2
/give username2 prize_sum2
```
e.g.
```
/give Zuza diadem
/give Zuza ciastko
/give Hubert zbroja
```

**Comment by wdoganowski** [comment]
Cały opis pokryty w #46
