### ISSUE TITLE
Create Teams view with additional data

### ISSUE THREAD

**Issue by wdoganowski** [tqZK/harc_game_web#34]
Informacje o drużynie (logo, nazwa, kolory, **drużynowy**, podatek)
**Statystyki drużyny (aktualny wynik)**
**Tabela ze statystykami graczy należących do danej drużyny**
**Zakupione przez drużynę ulepszenia wioski? (Zuza - zmodyfikować bazę danych)**

**Comment by wdoganowski** [comment]
Rozumiem to tak:

- Drużyna ma harcerzy
- Dokumentacja zadań ma harcerzy i zadania
- Zadania maja nagrody (punktacje)

1. Dla każdego harcerza trzeba podliczyć statystyki
2. Każdemu odjąć podatek i dodać drużynowemu
3. Potem podsumować dla drużyny 

Zakupionych ulepszeń jeszcze nie ma

**Comment by wdoganowski** [comment]
PR #42

**Comment by wdoganowski** [comment]
Nie jest liczony podatek. Czy to ma działać tak, że każdemu graczowi mam odjąć podatek drużyny i dodać go drużynowemu? Rozumiem, że nie może być więcej niż jeden drużynowy, @tqZK czy jest takie zabezpieczenie?

**Comment by zkunik** [comment]
Nie ma póki co takiego zabezpieczenia, ale też status drużynowego będą nadawać tylko admini, więc nie powinno być problemu.
Co do opisu działania podatku, to jest on opisany tutaj: https://github.com/tqZK/harc_game_web/issues/30
