### ISSUE TITLE
Create script to import task data from CSV to create JSON fixtures

### ISSUE THREAD

**Issue by zkunik** [tqZK/harc_game_web#36]
Data (such as tasks, wotd, etc.) will be provided by game organizers in Google Sheets. It can be exported to CSV (tab separated). We should create script that parses this CSV and creates JSON fixtures.

Data to test with: [zadania.txt](https://github.com/tqZK/harc_game_web/files/5566439/zadania.txt)

Each Task name should start with upper case.

Pandas library could be used

**Comment by wdoganowski** [comment]
+ Category

**Comment by wdoganowski** [comment]
Co z relacjami?

**Comment by zkunik** [comment]
Wotd data:
[hasla_dnia.txt](https://github.com/tqZK/harc_game_web/files/5577726/hasla_dnia.txt)
