### ISSUE TITLE
Prevent users from doing a task too many times

### ISSUE THREAD

**Issue by zkunik** [tqZK/harc_game_web#57]
Każde zadanie ma przypisane, jak często można je robić (bez ograniczeń, raz dziennie, raz w tygodniu). Przy wysyłaniu formularza zrobionego zadania (`complete_task()`) należy sprawdzić, czy użytkownik nie narusza tej zasady.
Przy czym dzień liczymy od 00:00 do 23:59, czyli jeżeli użytkownik zrobił zadanie (które można robić raz dziennie) o 23:30 w pn, to może zrobić to samo zadanie o 00:30 we wt (po godzinie), bo już liczy się kolejny dzień.
To samo tyczy się tygodnia sb-pt w kwestii zadań robionych raz w tygodniu.

**Comment by wdoganowski** [comment]
PR #61
